name: Build Plugin

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Build
        run: dotnet publish -p:EnableWindowsTargeting=true -c Release src -o plugin-output

      - name: Zip plugin
        run: zip -r Artemis.Plugins.Devices.Govee.zip plugin-output/

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: Artemis.Plugins.Devices.Govee
          path: Artemis.Plugins.Devices.Govee.zip
