name: Release Plugin

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Build
        run: dotnet publish -p:EnableWindowsTargeting=true -c Release src -o plugin-output

      - name: Zip plugin
        run: zip -r Artemis.Plugins.Devices.Govee.zip plugin-output/

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: Artemis.Plugins.Devices.Govee.zip
